### ISSUE TITLE
bytestring >= 0.10.8.0

### ISSUE THREAD

**Issue by peti** [silkapp/multipart#6]
I wonder where the `bytestring >= 0.10.8.0` constraint comes from. This lower bound cannot be satisfied by `ghc-7.10.3`. No big deal, of course, the compiler is very old ... I'm just curious whether that constraint is really necessary. See https://travis-ci.org/peti/multipart/builds/594576304 for the complete build log that shows the problem.

**Comment by hesselink** [comment]
This was done because the performance improvements in https://github.com/silkapp/multipart/pull/2 depend on `stripPrefix` which was added in that version.
